version: "3"
services:
  # Laravel Application
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel/laravel:/var/www/html
    ports:
      - "9000-9010:9000-9010"
    networks:
      - laravel-net

  # MySQL Database
  mysql:
    image: mysql:8
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel-net

  # Redis
  redis:
    image: redis
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - laravel-net

  # Nginx
  nginx:
    image: nginx
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./laravel/laravel/:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
    networks:
      - laravel-net

networks:
  laravel-net:


